export interface DomainAssignment {
  id: string;
  number: number;
  title: string;
  badge: string;
  difficulty: "Foundational" | "Intermediate" | "Advanced (Production)";
  estimatedHours: number;
  points: number;
  description: string;
  problemStatement: string;
  deliverables: string[];
  techRequirements: string[];
  submissionGuidelines: string;
}

export interface InternshipDomain {
  id: string;
  name: string;
  category: "Development" | "AI & Data" | "Mobile" | "DevOps & Security" | "Design";
  icon: string;
  tagline: string;
  description: string;
  techStack: string[];
  prerequisites: string[];
  capstoneProject: string;
  curriculum: {
    week: string;
    title: string;
    topics: string[];
  }[];
  assignments: DomainAssignment[];
  popular?: boolean;
}

export const INTERNSHIP_DOMAINS: InternshipDomain[] = [
  {
    id: "full-stack-web",
    name: "Full-Stack Web Development",
    category: "Development",
    icon: "⚡",
    popular: true,
    tagline: "Build scalable full-stack applications with Next.js 16, PostgreSQL & TypeScript",
    description:
      "Master modern web engineering from database schema design with Drizzle ORM and Neon PostgreSQL to reactive frontends with Next.js 16 App Router, Tailwind CSS, and zero-trust Better Auth.",
    techStack: ["Next.js 16", "TypeScript", "Tailwind CSS", "Neon PostgreSQL", "Drizzle ORM", "Better Auth"],
    prerequisites: ["HTML, CSS, JavaScript basics", "Basic understanding of React"],
    capstoneProject: "Production SaaS Workspace with Real-time Collaboration, Auth & Database",
    curriculum: [
      { week: "Week 1", title: "Modern TypeScript & Next.js App Router Architecture", topics: ["Server Components", "Layouts & Routing", "API Routes"] },
      { week: "Week 2", title: "Database Modeling & ORM Integration", topics: ["Neon PostgreSQL", "Drizzle ORM", "Migrations & Relations"] },
      { week: "Week 3", title: "Authentication & State Management", topics: ["Better Auth", "Session Management", "CRUD Operations"] },
      { week: "Week 4", title: "Deployment, CI/CD & Performance Tuning", topics: ["Vercel Edge Deployment", "Lighthouse 95+ Tuning", "Custom Domains"] },
    ],
    assignments: [
      {
        id: "fsw-asg-1",
        number: 1,
        title: "Database Schema & Auth Middleware Pipeline",
        badge: "Milestone 01: Core Architecture",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Architect a relational database schema using Drizzle ORM with secure session authentication and rate-limited API handlers.",
        problemStatement: "Design a multi-tenant user management schema with roles (Admin, Member, Guest), implement password hashing and session cookies with zero-trust validation, and build typed server actions for CRUD operations.",
        deliverables: [
          "Drizzle ORM schema definition with normalized tables and foreign keys",
          "Automated migration script connected to Neon Serverless PostgreSQL",
          "API route handlers with Zod request validation and error boundary wrapping",
        ],
        techRequirements: ["TypeScript", "Next.js 16 App Router", "Drizzle ORM", "Neon DB", "Zod"],
        submissionGuidelines: "Commit the schema definitions, migration files, and unit test suite to your repository under /packages/db.",
      },
      {
        id: "fsw-asg-2",
        number: 2,
        title: "Dynamic SaaS Workspace & Real-Time State Hub",
        badge: "Milestone 02: Systems Engineering",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Engineer an interactive data dashboard with server-side caching, dynamic filtering, optimistic UI updates, and pagination.",
        problemStatement: "Build a high-performance analytics workspace that loads 10,000+ data rows under 120ms, supports multi-filter faceted queries, instant search debouncing, and inline batch updates with rollback support.",
        deliverables: [
          "Responsive dashboard UI with dark cyber glassmorphism design tokens",
          "Server-side pagination and dynamic query string URL synchronization",
          "Optimistic UI state mutations with toast notification feedback",
        ],
        techRequirements: ["React 19", "Tailwind CSS", "Framer Motion", "Server Actions", "PostgreSQL Indexes"],
        submissionGuidelines: "Provide a working demo route with mock data seeding script and component documentation in README.md.",
      },
      {
        id: "fsw-asg-3",
        number: 3,
        title: "Production SaaS Capstone, Stripe/UPI Webhooks & Edge Deploy",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Deliver a production-ready SaaS application with payment gateway verification, email notifications, and edge caching.",
        problemStatement: "Complete end-to-end integration of the SaaS platform including payment webhook processing, automated transactional email dispatch via Resend, Lighthouse 95+ performance optimization, and custom domain deployment.",
        deliverables: [
          "Production deployment live on Vercel / Edge CDN",
          "Secure webhook verification handling idempotent payment transactions",
          "Comprehensive technical architecture documentation and exported ZIP codebase",
        ],
        techRequirements: ["Next.js 16", "Vercel Edge", "PostgreSQL", "Tailwind CSS", "Webhook Security"],
        submissionGuidelines: "Submit the public GitHub repo, live URL, and upload the complete source code archive (.zip) for admin evaluation.",
      },
    ],
  },
  {
    id: "ai-generative-agents",
    name: "AI & Generative AI Engineering",
    category: "AI & Data",
    icon: "🧠",
    popular: true,
    tagline: "Engineer autonomous AI agents, RAG vector pipelines & multi-model LLM systems",
    description:
      "Dive deep into building autonomous agent workflows using LangChain, OpenAI / Claude APIs, Pinecone vector embeddings, and streaming chat completions.",
    techStack: ["LangChain", "OpenAI / Anthropic APIs", "Pinecone Vector DB", "Python / FastAPI", "Next.js"],
    prerequisites: ["Python or JavaScript proficiency", "Basic understanding of APIs"],
    capstoneProject: "Autonomous Knowledge Retrieval & Multi-Agent Task Assistant (like Irus AI)",
    curriculum: [
      { week: "Week 1", title: "LLM Fundamentals & Prompt Engineering", topics: ["Structured Outputs", "Function Calling", "Token Optimization"] },
      { week: "Week 2", title: "RAG & Vector Embeddings Architecture", topics: ["Pinecone / Chroma", "Document Chunking", "Semantic Search"] },
      { week: "Week 3", title: "LangChain & Multi-Agent Orchestration", topics: ["Agent Chains", "Memory Stores", "Tool Use & Action Execution"] },
      { week: "Week 4", title: "Full-Stack Deployment & Evaluation", topics: ["FastAPI Backend", "Streaming Frontend UI", "Evaluation Metrics"] },
    ],
    assignments: [
      {
        id: "ai-asg-1",
        number: 1,
        title: "Semantic Vector Pipeline & Hybrid Document Chunker",
        badge: "Milestone 01: Vector Pipeline",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Build an ingestion pipeline that chunks PDF/Markdown documents, generates embeddings, and indexes them in a vector database.",
        problemStatement: "Implement semantic sliding-window text chunking with metadata preservation, compute dense vector embeddings with OpenAI text-embedding-3-small, and perform cosine similarity queries with Top-K re-ranking.",
        deliverables: [
          "Document parser with support for PDF, DOCX, and raw Markdown",
          "Vector index configuration in Pinecone / ChromaDB with namespace partitioning",
          "Benchmark script evaluating retrieval recall on sample domain queries",
        ],
        techRequirements: ["Python / TypeScript", "Pinecone / Chroma", "OpenAI API", "LangChain Document Loaders"],
        submissionGuidelines: "Submit the indexing script, embedding benchmarks, and sample corpus test results.",
      },
      {
        id: "ai-asg-2",
        number: 2,
        title: "Multi-Agent Orchestrator with Tool-Calling & Memory Store",
        badge: "Milestone 02: Agent Architecture",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Develop an autonomous multi-agent graph with specialized subagents, dynamic tool execution, and episodic conversation memory.",
        problemStatement: "Construct an orchestrator where a planner agent decomposes user requests, delegates to research and calculation subagents, executes Python/SQL sandboxed tools, and synthesizes structured JSON results.",
        deliverables: [
          "StateGraph / LangGraph implementation with cyclic tool-calling loops",
          "Persistent thread memory store using Redis / PostgreSQL",
          "Defensive guardrails preventing prompt injection and hallucinated outputs",
        ],
        techRequirements: ["LangChain / LangGraph", "FastAPI", "Redis / PostgreSQL", "Pydantic"],
        submissionGuidelines: "Include architecture diagram, agent interaction logs, and automated evaluation test cases in your ZIP file.",
      },
      {
        id: "ai-asg-3",
        number: 3,
        title: "Streaming AI Command Center Capstone & Edge Evaluation",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Deploy an end-to-end AI Copilot with real-time token streaming, artifact rendering, and RAG evaluation metrics.",
        problemStatement: "Deliver a full-stack AI Copilot (inspired by Irus AI) featuring SSE streaming responses, inline markdown/code execution artifacts, Ragas retrieval evaluation metrics, and low-latency cloud deployment.",
        deliverables: [
          "Full-stack web application with streaming chat UI and syntax highlighting",
          "Ragas / TruLens evaluation report verifying answer relevancy > 0.90",
          "Production deployment URL and exported source code ZIP archive",
        ],
        techRequirements: ["Next.js", "FastAPI / Node.js", "Vercel / Render", "Ragas", "OpenAI / Claude"],
        submissionGuidelines: "Submit live deployment link, GitHub repository, and attach the complete ZIP package for admin verification.",
      },
    ],
  },
  {
    id: "machine-learning",
    name: "Machine Learning & Deep Learning",
    category: "AI & Data",
    icon: "🔬",
    popular: true,
    tagline: "Train, evaluate & deploy neural networks and predictive ML models",
    description:
      "Explore supervised, unsupervised learning, computer vision, and NLP using PyTorch, TensorFlow, and Scikit-Learn with real-world datasets.",
    techStack: ["Python", "PyTorch", "TensorFlow", "Scikit-Learn", "Pandas", "Streamlit"],
    prerequisites: ["Python programming", "Linear algebra & statistics basics"],
    capstoneProject: "Computer Vision Receipt OCR & Predictive Financial Classifier",
    curriculum: [
      { week: "Week 1", title: "Data Wrangling & Exploratory Analysis", topics: ["Pandas & NumPy", "Feature Engineering", "Data Cleaning"] },
      { week: "Week 2", title: "Classical ML Algorithms", topics: ["Regression & Classification", "Random Forests", "Hyperparameter Tuning"] },
      { week: "Week 3", title: "Deep Learning & Neural Networks", topics: ["PyTorch Tensors", "CNNs & Image Processing", "Model Training"] },
      { week: "Week 4", title: "Model Inference & Web API Deployment", topics: ["ONNX Runtime", "FastAPI Endpoints", "Streamlit Dashboard"] },
    ],
    assignments: [
      {
        id: "ml-asg-1",
        number: 1,
        title: "Exploratory Feature Engineering & Classifier Benchmark",
        badge: "Milestone 01: Data Pipeline",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Clean complex tabular datasets, engineer predictive features, and train baseline classical ML models.",
        problemStatement: "Handle missing values, categorical encodings, outlier normalization on a real-world financial/healthcare dataset, train XGBoost / Random Forest models, and evaluate with ROC-AUC and F1-score.",
        deliverables: [
          "Jupyter Notebook with EDA visualizations (correlation heatmaps, distributions)",
          "Scikit-Learn preprocessing Pipeline with cross-validation splits",
          "Model comparison report with precision-recall curves and feature importance charts",
        ],
        techRequirements: ["Python", "Pandas", "Scikit-Learn", "XGBoost", "Matplotlib / Seaborn"],
        submissionGuidelines: "Commit the cleaned data script, Jupyter analysis notebook, and serialized model weights.",
      },
      {
        id: "ml-asg-2",
        number: 2,
        title: "Deep Convolutional Neural Network & Transfer Learning",
        badge: "Milestone 02: Deep Learning",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Fine-tune a deep vision neural network (ResNet/EfficientNet) with data augmentations and learning rate scheduling.",
        problemStatement: "Train a PyTorch image classification model on custom image data, implement CutMix/MixUp augmentations, track training loss/accuracy with TensorBoard, and achieve >94% validation accuracy.",
        deliverables: [
          "PyTorch training and validation loop with early stopping and checkpointing",
          "Transfer learning script fine-tuning pretrained weights",
          "Confusion matrix and Grad-CAM activation heatmaps showing model attention",
        ],
        techRequirements: ["PyTorch", "Torchvision", "TensorBoard", "Albumentations", "CUDA/MPS"],
        submissionGuidelines: "Provide model training logs, checkpoint files, and evaluation scripts in your ZIP archive.",
      },
      {
        id: "ml-asg-3",
        number: 3,
        title: "Optimized ONNX Inference Engine & Streamlit Web Studio",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Export models to ONNX runtime, package a FastAPI inference service, and deploy an interactive web dashboard.",
        problemStatement: "Quantize model weights (INT8/FP16) for sub-30ms CPU inference, build a REST API endpoint accepting image/tabular inputs, and build a live Streamlit/React web application for real-time predictions.",
        deliverables: [
          "ONNX quantized model artifact with benchmark report",
          "FastAPI prediction endpoint with input validation and latency metrics",
          "Live deployed Streamlit/HuggingFace Spaces demo and ZIP project source",
        ],
        techRequirements: ["ONNX Runtime", "FastAPI", "Streamlit", "Docker", "Python 3.11"],
        submissionGuidelines: "Upload the project ZIP containing code, Dockerfile, model export script, and live demo link.",
      },
    ],
  },
  {
    id: "data-analytics",
    name: "Data Analytics & Business Intelligence",
    category: "AI & Data",
    icon: "📊",
    popular: true,
    tagline: "Transform complex data into actionable executive insights with SQL & PowerBI",
    description:
      "Master end-to-end data analytics: write advanced SQL queries, clean raw datasets with Python/Pandas, and craft interactive dashboards with PowerBI / Tableau.",
    techStack: ["SQL (PostgreSQL)", "Python (Pandas, Seaborn)", "PowerBI", "Tableau", "Excel / Google Sheets"],
    prerequisites: ["Basic logic & spreadsheet familiarity"],
    capstoneProject: "Global Enterprise Revenue & User Retention Analytics BI Suite",
    curriculum: [
      { week: "Week 1", title: "Advanced SQL & Relational Querying", topics: ["Joins & Subqueries", "Window Functions", "Aggregations"] },
      { week: "Week 2", title: "Python for Data Analysis", topics: ["Pandas DataFrames", "Data Cleaning", "Matplotlib Visualizations"] },
      { week: "Week 3", title: "Interactive Business Intelligence", topics: ["PowerBI Dashboards", "DAX Formulas", "KPI Tracking"] },
      { week: "Week 4", title: "Storytelling & Executive Reporting", topics: ["Cohort Retention", "A/B Testing Analysis", "Final Capstone Presentation"] },
    ],
    assignments: [
      {
        id: "da-asg-1",
        number: 1,
        title: "Relational SQL Transformation & Window Analytics",
        badge: "Milestone 01: SQL Mastery",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Write complex analytical SQL queries using CTEs, window functions, and rolling aggregation metrics.",
        problemStatement: "Given a 500,000-row e-commerce transaction dataset, calculate MoM revenue growth, 30-day rolling customer churn rate, top percentile customers (NTILE), and average order frequency per cohort.",
        deliverables: [
          "SQL migration and view scripts with documented query logic",
          "Query optimization analysis with EXPLAIN ANALYZE execution plans",
          "Exported summary datasets and validation checks",
        ],
        techRequirements: ["PostgreSQL / BigQuery", "Advanced SQL CTEs", "Window Functions", "Data Modeling"],
        submissionGuidelines: "Submit the SQL scripts (.sql), query output data files, and performance documentation.",
      },
      {
        id: "da-asg-2",
        number: 2,
        title: "Cohort Retention & Statistical Hypothesis Testing",
        badge: "Milestone 02: Statistical Analysis",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Conduct longitudinal cohort retention analysis and A/B test statistical significance testing in Python.",
        problemStatement: "Perform user cohort retention matrix analysis, calculate customer lifetime value (LTV:CAC), and evaluate conversion rate significance using two-tailed Z-tests and bootstrapping.",
        deliverables: [
          "Python analytics script producing cohort retention heatmaps",
          "A/B test statistical analysis report with p-values and confidence intervals",
          "Executive summary slide deck highlighting 3 key actionable business recommendations",
        ],
        techRequirements: ["Python", "Pandas", "SciPy Stats", "Seaborn", "Jupyter Notebook"],
        submissionGuidelines: "Include the Jupyter notebook, high-resolution visual charts, and findings report in your ZIP archive.",
      },
      {
        id: "da-asg-3",
        number: 3,
        title: "Executive PowerBI / Tableau BI Dashboard & Presentation",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Build an interactive, multi-tab Business Intelligence dashboard with dynamic DAX metrics and drill-through filters.",
        problemStatement: "Create an enterprise executive dashboard tracking revenue, customer health, regional heatmaps, and inventory turnover with real-time parameters and interactive cross-filtering.",
        deliverables: [
          "Interactive PowerBI (.pbix) or Tableau (.twbx) workbook file",
          "Custom DAX measure formulas documented in a central dictionary",
          "Recorded 5-minute video walkthrough or PDF presentation of executive insights",
        ],
        techRequirements: ["PowerBI / Tableau", "DAX / Calculated Fields", "Data Modeling Star Schema", "Figma Dashboard Layout"],
        submissionGuidelines: "Upload the dashboard workbook, documentation PDF, and project ZIP archive for admin evaluation.",
      },
    ],
  },
  {
    id: "android-development",
    name: "Android Native Development",
    category: "Mobile",
    icon: "📱",
    popular: true,
    tagline: "Craft high-performance native Android apps using Kotlin & Jetpack Compose",
    description:
      "Learn modern Android architecture with Kotlin, Jetpack Compose declarative UI, Room database, Coroutines, and REST API integration with Retrofit.",
    techStack: ["Kotlin", "Jetpack Compose", "Android Studio", "Retrofit", "Room DB", "Coroutines"],
    prerequisites: ["Object-Oriented Programming (Java or Kotlin)"],
    capstoneProject: "Offline-First Native Android Productivity & Habit Tracking App",
    curriculum: [
      { week: "Week 1", title: "Kotlin Essentials & Jetpack Compose Basics", topics: ["Kotlin Syntax", "Composable Functions", "State & Recomposition"] },
      { week: "Week 2", title: "Navigation & UI Component Architecture", topics: ["Navigation Compose", "Scaffolds & TopBars", "Theming & Dark Mode"] },
      { week: "Week 3", title: "Networking & Local Persistence", topics: ["Retrofit API Client", "Coroutines & Flow", "Room SQLite Database"] },
      { week: "Week 4", title: "MVVM Architecture & APK Build Release", topics: ["ViewModel & StateFlow", "Dependency Injection (Hilt)", "Signed APK Generation"] },
    ],
    assignments: [
      {
        id: "and-asg-1",
        number: 1,
        title: "Jetpack Compose Declarative UI & Navigation Graph",
        badge: "Milestone 01: Mobile UI System",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Design a Material 3 native UI using Jetpack Compose with reactive state management and type-safe navigation.",
        problemStatement: "Build a multi-screen mobile UI featuring dark mode support, animated bottom navigation bars, custom canvas charts, and form validation with Compose StateFlow.",
        deliverables: [
          "Composable UI screens with Material 3 typography and theme system",
          "Navigation Compose graph with animated screen transitions",
          "Unit tests verifying ViewModel state emission and form validation",
        ],
        techRequirements: ["Kotlin", "Jetpack Compose", "Material 3", "Navigation Compose", "StateFlow"],
        submissionGuidelines: "Commit the Compose code, screen layout previews, and test cases.",
      },
      {
        id: "and-asg-2",
        number: 2,
        title: "Room SQLite Database & Offline-First Sync Engine",
        badge: "Milestone 02: Persistence & Sync",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Implement local caching with Room DB, background Coroutine workers, and Retrofit network synchronization.",
        problemStatement: "Build an offline-first data repository that displays cached Room database entries instantly, fetches remote delta updates via Retrofit in background Coroutines, and resolves merge conflicts.",
        deliverables: [
          "Room database entities, DAOs, and migration strategies",
          "Repository pattern implementation with Kotlin Flow emitting Resource<T>",
          "WorkManager background worker scheduling automated sync jobs",
        ],
        techRequirements: ["Room DB", "Kotlin Coroutines & Flow", "Retrofit & OkHttp", "WorkManager", "Hilt DI"],
        submissionGuidelines: "Include the repository code, database schema migrations, and sync demo recordings.",
      },
      {
        id: "and-asg-3",
        number: 3,
        title: "Production Android Capstone & Signed Release APK",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Deliver a complete native Android application with clean architecture, ProGuard obfuscation, and signed APK generation.",
        problemStatement: "Complete full integration of the native Android app with push notifications, edge-to-edge drawing, ProGuard shrinking, and generate a signed release APK ready for Google Play distribution.",
        deliverables: [
          "Full Android Studio project codebase in MVVM Clean Architecture",
          "Signed production release APK / AAB build",
          "README documentation with architecture diagrams and feature screenshots",
        ],
        techRequirements: ["Android Studio", "Kotlin 2.0", "Jetpack Compose", "ProGuard / R8", "Signed APK"],
        submissionGuidelines: "Upload the GitHub repo, signed APK binary, and project ZIP archive for admin verification.",
      },
    ],
  },
  {
    id: "java-backend",
    name: "Java Enterprise & Backend Development",
    category: "Development",
    icon: "☕",
    popular: true,
    tagline: "Build enterprise REST APIs and microservices with Java & Spring Boot",
    description:
      "Deep dive into enterprise software engineering with Core Java, Spring Boot 3, Spring Data JPA, Hibernate, JWT Security, and PostgreSQL.",
    techStack: ["Core Java 21", "Spring Boot 3", "Spring Security (JWT)", "PostgreSQL", "Hibernate", "Maven"],
    prerequisites: ["Core Java fundamentals", "Basic OOP principles"],
    capstoneProject: "Enterprise E-Commerce Microservice Backend with JWT & Payment Webhooks",
    curriculum: [
      { week: "Week 1", title: "Advanced Java & Spring Boot Setup", topics: ["Java 21 Features", "Spring Boot Starter", "Dependency Injection"] },
      { week: "Week 2", title: "RESTful Web Services & JPA", topics: ["Spring MVC Controllers", "Spring Data JPA", "PostgreSQL Queries"] },
      { week: "Week 3", title: "Security & Authentication", topics: ["Spring Security Filter Chain", "JWT Tokens", "Role-Based Access Control"] },
      { week: "Week 4", title: "Testing, Swagger Documentation & Docker", topics: ["JUnit 5 & Mockito", "Swagger OpenAPI", "Dockerizing Spring App"] },
    ],
    assignments: [
      {
        id: "jav-asg-1",
        number: 1,
        title: "Spring Data JPA Relational Model & Query Optimization",
        badge: "Milestone 01: Entity Modeling",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Design JPA entities with Hibernate relationships, custom JPQL queries, and database pagination.",
        problemStatement: "Create an enterprise entity model with @OneToMany and @ManyToMany mappings, avoid N+1 query traps using @EntityGraph and join fetches, and implement transactional service boundaries.",
        deliverables: [
          "Spring Boot 3 project with JPA entity models and DTO mappings (MapStruct)",
          "Flyway / Liquibase database migration scripts",
          "Repository test suite using Testcontainers and PostgreSQL",
        ],
        techRequirements: ["Java 21", "Spring Boot 3", "Spring Data JPA", "PostgreSQL", "Flyway"],
        submissionGuidelines: "Commit the Spring Boot project, JPA repositories, and migration scripts.",
      },
      {
        id: "jav-asg-2",
        number: 2,
        title: "Spring Security 6 Stateless JWT & RBAC Authorization",
        badge: "Milestone 02: Enterprise Security",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Configure Spring Security filter chain with stateless JWT token validation, refresh tokens, and method-level security.",
        problemStatement: "Implement a security filter chain with BCrypt password hashing, JWT token rotation, role-based endpoint permissions (@PreAuthorize), and centralized global exception handling.",
        deliverables: [
          "Spring Security 6 SecurityFilterChain configuration",
          "JWT provider and filter with token expiration and blacklist revocation",
          "Global @RestControllerAdvice handling custom business exceptions",
        ],
        techRequirements: ["Spring Security 6", "jjwt (Java JWT)", "BCrypt", "REST Controllers", "Mockito"],
        submissionGuidelines: "Include the security module, token unit tests, and Postman collection in your ZIP file.",
      },
      {
        id: "jav-asg-3",
        number: 3,
        title: "Enterprise Microservices Capstone, Docker & Swagger OpenAPI",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Package the enterprise backend into a containerized microservice with Swagger OpenAPI specs and payment webhooks.",
        problemStatement: "Deliver a production enterprise backend service with complete Swagger OpenAPI 3.0 documentation, multi-stage Docker build, and robust unit/integration tests with >85% code coverage.",
        deliverables: [
          "Complete Spring Boot Maven codebase with Swagger UI enabled",
          "Multi-stage Dockerfile and docker-compose.yml for PostgreSQL & Redis",
          "JUnit 5 & Mockito test suite passing with code coverage report",
        ],
        techRequirements: ["Spring Boot 3", "Docker", "OpenAPI 3.0 / Swagger", "JUnit 5", "Maven"],
        submissionGuidelines: "Upload the project ZIP containing code, Docker configurations, and OpenAPI JSON spec.",
      },
    ],
  },
  {
    id: "mobile-app-crossplatform",
    name: "Mobile App Development (React Native / Flutter)",
    category: "Mobile",
    icon: "📲",
    tagline: "Develop cross-platform iOS & Android mobile apps with one codebase",
    description:
      "Build fluid, native-feel mobile applications using React Native / Expo, native device APIs, push notifications, and offline caching.",
    techStack: ["React Native", "Expo", "TypeScript", "Tailwind (NativeWind)", "AsyncStorage", "Firebase"],
    prerequisites: ["JavaScript & React fundamentals"],
    capstoneProject: "Cross-Platform Social Fitness & Workout Tracker App",
    curriculum: [
      { week: "Week 1", title: "React Native & Expo Ecosystem", topics: ["Core Components", "Flexbox Layouts", "Expo Router"] },
      { week: "Week 2", title: "Native Device APIs & Animations", topics: ["Camera & Geolocation", "Reanimated 3", "Gestures"] },
      { week: "Week 3", title: "Backend Sync & Authentication", topics: ["Firebase Auth / Supabase", "REST API Ingestion", "Offline Caching"] },
      { week: "Week 4", title: "App Optimization & Expo EAS Build", topics: ["Performance Profiling", "Push Notifications", "EAS Build Workflow"] },
    ],
    assignments: [
      {
        id: "rn-asg-1",
        number: 1,
        title: "Cross-Platform Fluid UI & Gesture Animations",
        badge: "Milestone 01: Mobile UI System",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Craft a 60fps mobile application layout with React Native Reanimated, gesture handlers, and theme toggling.",
        problemStatement: "Build responsive cross-platform screens using NativeWind/Tailwind, spring physics swipe-to-delete gestures with React Native Gesture Handler, and persistent dark/light theme switching.",
        deliverables: [
          "Expo Router file-based navigation structure",
          "Smooth interactive gesture cards using Reanimated 3",
          "Shared design token theme system with dark mode",
        ],
        techRequirements: ["React Native", "Expo", "TypeScript", "Reanimated 3", "NativeWind"],
        submissionGuidelines: "Commit the Expo mobile codebase, component hierarchy, and demo video preview.",
      },
      {
        id: "rn-asg-2",
        number: 2,
        title: "Hardware Device APIs & Real-Time Cloud Sync",
        badge: "Milestone 02: Hardware Integration",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Integrate native device sensors (Camera, Location, Accelerometer) and synchronize state with a cloud backend.",
        problemStatement: "Implement camera image capture with client-side compression, real-time geolocation tracking with background task permissions, and secure token authentication with Supabase / Firebase.",
        deliverables: [
          "Camera & Media library integration with permission handling",
          "Background geolocation tracker with battery-efficient sampling",
          "Offline persistent cache with automatic online sync queue",
        ],
        techRequirements: ["Expo Camera / Location", "Supabase / Firebase", "AsyncStorage", "TypeScript"],
        submissionGuidelines: "Provide mobile code, permission configurations, and device testing logs in your ZIP file.",
      },
      {
        id: "rn-asg-3",
        number: 3,
        title: "Production Mobile Capstone & Expo EAS Cloud Build",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Finalize the cross-platform application, implement push notifications, and build a standalone preview APK/IPA.",
        problemStatement: "Complete full integration of the mobile application with Expo Push Notifications, app store metadata assets, and generate a standalone Android APK via Expo Application Services (EAS Build).",
        deliverables: [
          "Full React Native / Expo codebase with 0 TypeScript/lint errors",
          "Generated standalone APK build file or Expo Snack / EAS preview link",
          "Project README with architectural decisions and exported ZIP archive",
        ],
        techRequirements: ["React Native", "Expo EAS Build", "Push Notifications", "TypeScript", "Android APK"],
        submissionGuidelines: "Upload GitHub repository, EAS build link, and the complete source code ZIP archive for admin review.",
      },
    ],
  },
  {
    id: "cloud-devsecops",
    name: "Cloud, DevOps & DevSecOps Engineering",
    category: "DevOps & Security",
    icon: "☁️",
    tagline: "Automate CI/CD pipelines, container orchestration & zero-trust security",
    description:
      "Learn to containerize applications with Docker, build automated GitHub Actions workflows, implement security SAST scanning, and deploy to Kubernetes & Edge CDNs.",
    techStack: ["Docker", "Kubernetes", "GitHub Actions", "Vercel / AWS", "Linux / Bash", "Trivy / SonarQube"],
    prerequisites: ["Basic Linux command line knowledge", "Git fundamentals"],
    capstoneProject: "Zero-Downtime Automated CI/CD Pipeline with Security Scanning & Monitoring",
    curriculum: [
      { week: "Week 1", title: "Linux Systems & Docker Containerization", topics: ["Dockerfiles & Multi-stage Builds", "Docker Compose", "Volume Management"] },
      { week: "Week 2", title: "CI/CD with GitHub Actions", topics: ["Automated Testing Workflows", "Build Triggers", "Matrix Builds"] },
      { week: "Week 3", title: "DevSecOps & SAST Security Scanning", topics: ["Secret Detection (Gitleaks)", "Container Vulnerability Scanning", "SSL Hardening"] },
      { week: "Week 4", title: "Cloud Deployment & Telemetry", topics: ["Edge CDN Config", "Serverless Infrastructure", "Grafana / Prometheus Logging"] },
    ],
    assignments: [
      {
        id: "dso-asg-1",
        number: 1,
        title: "Multi-Stage Docker Containerization & Compose Cluster",
        badge: "Milestone 01: Containerization",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Create lightweight, secure multi-stage Docker images and orchestrate a multi-service stack with Docker Compose.",
        problemStatement: "Optimize a Node.js/Python application container down to <100MB using Alpine/Distroless bases, enforce non-root user execution, and configure a Docker Compose stack with healthchecks, volumes, and networks.",
        deliverables: [
          "Optimized multi-stage Dockerfile with layer caching strategy",
          "docker-compose.yml orchestrating Web App, PostgreSQL, and Redis",
          "Container vulnerability audit log using Trivy / Docker Scout",
        ],
        techRequirements: ["Docker", "Docker Compose", "Linux / Bash", "Trivy", "Security Best Practices"],
        submissionGuidelines: "Commit the Docker configuration files, compose manifests, and build size comparisons.",
      },
      {
        id: "dso-asg-2",
        number: 2,
        title: "Automated GitHub Actions CI/CD Pipeline & SAST Audit",
        badge: "Milestone 02: DevSecOps Pipeline",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Construct an automated GitHub Actions pipeline with unit testing matrix, secret scanning, and automated container pushes.",
        problemStatement: "Build a GitHub Actions workflow that triggers on pull requests, runs linting/unit tests in parallel matrix, executes Gitleaks secret scanning and SonarQube SAST code analysis, and pushes signed images to GitHub Container Registry (GHCR).",
        deliverables: [
          ".github/workflows CI/CD workflow definitions with branch protection gates",
          "Automated SAST security report blocking PRs with high/critical vulnerabilities",
          "Automated release tagging with semantic versioning changelogs",
        ],
        techRequirements: ["GitHub Actions", "Gitleaks", "SonarQube / CodeQL", "GHCR / Docker Hub", "YAML"],
        submissionGuidelines: "Include workflow YAML files, successful GitHub Actions execution run links, and security reports.",
      },
      {
        id: "dso-asg-3",
        number: 3,
        title: "Kubernetes Manifests & Production Telemetry Capstone",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Deploy microservices onto Kubernetes with zero-downtime rolling updates, Ingress SSL, and Prometheus/Grafana monitoring.",
        problemStatement: "Author production Kubernetes manifests (Deployments, Services, Ingress, ConfigMaps, Secrets, HPA autoscaling), simulate zero-downtime rolling upgrades, and configure Prometheus metrics collection with Grafana dashboards.",
        deliverables: [
          "Complete Kubernetes YAML manifests directory (K8s / Helm chart)",
          "Prometheus monitoring configuration with custom latency/error rate alerts",
          "Architecture defense document and exported project ZIP archive",
        ],
        techRequirements: ["Kubernetes (Minikube / EKS / K3s)", "Prometheus", "Grafana", "Helm", "NGINX Ingress"],
        submissionGuidelines: "Upload the project ZIP containing Kubernetes manifests, Helm charts, monitoring configs, and repo link.",
      },
    ],
  },
  {
    id: "uiux-3d-design",
    name: "UI/UX & 3D Interactive Design",
    category: "Design",
    icon: "🎨",
    tagline: "Create high-converting cyber glassmorphism UIs & Three.js 3D web scenes",
    description:
      "Bridge design and engineering: craft stunning design systems in Figma and bring them to life on the web using Three.js, React Three Fiber, and Framer Motion.",
    techStack: ["Figma", "Three.js", "React Three Fiber", "Framer Motion", "Tailwind CSS", "GLSL Shaders"],
    prerequisites: ["Basic design sensibility & HTML/CSS familiarity"],
    capstoneProject: "Cyberpunk Interactive 3D Landing Page with Particle Effects & Custom Shaders",
    curriculum: [
      { week: "Week 1", title: "Modern UI/UX Principles & Figma Mastery", topics: ["Glassmorphism & Cyber Aesthetics", "Design Systems & Tokens", "Component Variants"] },
      { week: "Week 2", title: "Framer Motion & Micro-Interactions", topics: ["Scroll-Linked Animations", "Layout Animations", "Gesture Physics"] },
      { week: "Week 3", title: "Three.js & React Three Fiber", topics: ["3D Meshes & Geometry", "Lighting & Post-Processing Bloom", "Particle Systems"] },
      { week: "Week 4", title: "Interactive 3D Portfolio Capstone", topics: ["OrbitControls", "Performance Optimization", "Responsive 3D Canvas"] },
    ],
    assignments: [
      {
        id: "ui-asg-1",
        number: 1,
        title: "Enterprise Cyber Glassmorphism Design System in Figma",
        badge: "Milestone 01: Design Systems",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Design a complete responsive design system in Figma with color variables, typography scales, and interactive components.",
        problemStatement: "Create a design system featuring dark neon aesthetics, glassmorphic card overlays, interactive button state variants (default, hover, active, disabled), and 12-column responsive layout grids for desktop and mobile.",
        deliverables: [
          "Figma design system file with auto-layout components and design tokens",
          "Interactive Figma prototype demonstrating core user flows and modals",
          "Design specification sheet with WCAG 2.1 AA accessibility contrast checks",
        ],
        techRequirements: ["Figma", "Design Tokens", "Auto Layout", "Prototyping", "WCAG AA"],
        submissionGuidelines: "Submit the Figma community / view-only link, asset export package, and token documentation.",
      },
      {
        id: "ui-asg-2",
        number: 2,
        title: "Scroll-Linked Micro-Interactions with Framer Motion",
        badge: "Milestone 02: Interactive Engineering",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Translate high-fidelity Figma designs into responsive React components with physics-based scroll animations and page transitions.",
        problemStatement: "Build a frontend application featuring scroll-linked progress indicators, parallax element staggering, layout spring animations (layoutId), and custom cursor effects running smoothly at 60fps.",
        deliverables: [
          "Next.js / React interactive landing page with Framer Motion animations",
          "Custom hooks for scroll velocity and viewport intersection detection",
          "Mobile touch gesture optimization with reduced motion accessibility support",
        ],
        techRequirements: ["React 19", "Framer Motion", "Tailwind CSS", "TypeScript"],
        submissionGuidelines: "Include the interactive code, component library, and screen recordings in your ZIP file.",
      },
      {
        id: "ui-asg-3",
        number: 3,
        title: "Interactive Three.js 3D Scene Capstone & Post-Processing",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Create an interactive 3D web experience with React Three Fiber, custom GLSL vertex/fragment shaders, and Unreal bloom post-processing.",
        problemStatement: "Deliver a 3D web showcase featuring interactive particle meshes that react to cursor movements, dynamic lighting and camera OrbitControls, GLSL noise shaders, and 60fps performance on mobile browsers.",
        deliverables: [
          "Production 3D web application deployed live on Vercel / Netlify",
          "Custom GLSL shader code documented with mathematical derivations",
          "Complete project source code ZIP package and GitHub repository link",
        ],
        techRequirements: ["Three.js", "React Three Fiber (R3F)", "@react-three/drei", "GLSL Shaders", "Post-processing"],
        submissionGuidelines: "Upload the live URL, GitHub repository, and full source code ZIP archive for admin review.",
      },
    ],
  },
  {
    id: "python-backend",
    name: "Python Backend & Automation Engineering",
    category: "Development",
    icon: "🐍",
    tagline: "Build high-throughput async APIs, web scrapers & automated bot workflows",
    description:
      "Master Python for modern backend development with FastAPI, Asyncio, SQLAlchemy, PostgreSQL, web scraping with Playwright, and scheduled background workers.",
    techStack: ["Python 3.12", "FastAPI", "Asyncio", "SQLAlchemy", "PostgreSQL", "Playwright"],
    prerequisites: ["Basic Python knowledge"],
    capstoneProject: "Automated Multi-Source Web Intelligence & News Aggregator API",
    curriculum: [
      { week: "Week 1", title: "Modern Python & Async Programming", topics: ["Type Hints & Pydantic", "Asyncio Coroutines", "Error Handling"] },
      { week: "Week 2", title: "High-Performance APIs with FastAPI", topics: ["Dependency Injection", "OpenAPI Docs", "JWT Authentication"] },
      { week: "Week 3", title: "Web Scraping & Browser Automation", topics: ["Playwright / BeautifulSoup", "Headless Browsers", "Anti-Bot Handling"] },
      { week: "Week 4", title: "Database Sync & Worker Deployment", topics: ["SQLAlchemy ORM", "Cron Automation", "Cloud Deployment"] },
    ],
    assignments: [
      {
        id: "py-asg-1",
        number: 1,
        title: "Async FastAPI Microservice & Pydantic V2 Validation",
        badge: "Milestone 01: Async REST API",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Develop a high-concurrency asynchronous REST API with FastAPI, Pydantic V2 schemas, and dependency injection.",
        problemStatement: "Build an API handling asynchronous database queries with SQLAlchemy 2.0 and asyncpg, enforce strict request validation with Pydantic, and implement JWT authentication with custom middleware logging.",
        deliverables: [
          "FastAPI application structure with modular routers and dependency injection",
          "Async SQLAlchemy models and Alembic database migration scripts",
          "Pytest async test suite with mocked database fixtures",
        ],
        techRequirements: ["Python 3.12", "FastAPI", "Pydantic V2", "SQLAlchemy 2.0", "Asyncpg"],
        submissionGuidelines: "Commit the FastAPI source code, Alembic migrations, and pytest test suite.",
      },
      {
        id: "py-asg-2",
        number: 2,
        title: "Headless Browser Automation & Anti-Bot Scraping Worker",
        badge: "Milestone 02: Web Automation",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Build an asynchronous web scraping engine with Playwright, proxy rotation, and structured data normalization.",
        problemStatement: "Extract real-time data across dynamic JavaScript-rendered target websites using headless Playwright, implement user-agent spoofing and exponential retry backoff, and save normalized records to PostgreSQL.",
        deliverables: [
          "Asynchronous Playwright worker with error handling and screenshot debugging",
          "Data cleaning and deduplication pipeline validating structured output schemas",
          "Benchmarking script demonstrating extraction speed of 500+ pages/minute",
        ],
        techRequirements: ["Playwright Python", "Asyncio", "BeautifulSoup4", "PostgreSQL", "Pydantic"],
        submissionGuidelines: "Include scraper scripts, schema definitions, and sample scraped datasets in your ZIP file.",
      },
      {
        id: "py-asg-3",
        number: 3,
        title: "Background Task Queue & Production Deployment Capstone",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Deploy a production-grade automated intelligence backend with Celery/RQ job queues, Redis, and Docker containerization.",
        problemStatement: "Integrate a distributed asynchronous task queue with Redis, schedule periodic cron jobs for automatic web data refreshes, containerize the entire stack, and deploy to cloud infrastructure with live Swagger documentation.",
        deliverables: [
          "Full Python backend with Celery / Redis background worker queue",
          "Docker Compose configuration running FastAPI, Celery Worker, Redis, and Postgres",
          "Live deployed API documentation URL and exported project ZIP archive",
        ],
        techRequirements: ["FastAPI", "Celery / Redis", "Docker", "PostgreSQL", "Python 3.12"],
        submissionGuidelines: "Upload the GitHub repo, live API docs link, and complete project ZIP archive for admin review.",
      },
    ],
  },
  {
    id: "cyber-security",
    name: "Cyber Security & Ethical Hacking",
    category: "DevOps & Security",
    icon: "🛡️",
    tagline: "Audit web applications, identify vulnerabilities & enforce zero-trust defense",
    description:
      "Understand ethical hacking methodology, OWASP Top 10 vulnerabilities (SQLi, XSS, CSRF, IDOR), network packet analysis with Wireshark, and security penetration testing.",
    techStack: ["OWASP Top 10", "Burp Suite", "Nmap", "Wireshark", "Linux Security", "Penetration Testing"],
    prerequisites: ["Basic networking & web fundamentals"],
    capstoneProject: "Comprehensive Web Application Penetration Test Report & Security Audit",
    curriculum: [
      { week: "Week 1", title: "Networking & Security Fundamentals", topics: ["TCP/IP & DNS", "Packet Analysis with Wireshark", "Port Scanning with Nmap"] },
      { week: "Week 2", title: "OWASP Top 10 Web Vulnerabilities", topics: ["SQL Injection", "Cross-Site Scripting (XSS)", "CSRF & Session Hijacking"] },
      { week: "Week 3", title: "Hands-on Web Pentesting with Burp Suite", topics: ["Intercepting Proxies", "Fuzzing & Payload Injection", "Auth Bypass Tests"] },
      { week: "Week 4", title: "Remediation, Audit Reporting & Hardening", topics: ["Zero-Trust Defense", "Writing Professional Audit Reports", "Security Headers"] },
    ],
    assignments: [
      {
        id: "sec-asg-1",
        number: 1,
        title: "Network Reconnaissance & Packet Capture Telemetry Analysis",
        badge: "Milestone 01: Recon & Traffic Analysis",
        difficulty: "Foundational",
        estimatedHours: 40,
        points: 6,
        description: "Perform network port scanning with Nmap and analyze protocol packet flows with Wireshark.",
        problemStatement: "Conduct reconnaissance against a target lab network, identify open ports and service versions with Nmap NSE scripts, capture and decrypt TLS/HTTP traffic in Wireshark, and document security anomalies.",
        deliverables: [
          "Nmap scan report detailing open attack vectors and CVE vulnerabilities",
          "Wireshark packet capture analysis (.pcapng) identifying plaintext credentials",
          "Remediation checklist for network firewall and port hardening",
        ],
        techRequirements: ["Nmap", "Wireshark", "Linux", "TCP/IP Protocol Suite", "Bash"],
        submissionGuidelines: "Commit scan outputs, packet analysis summary, and network hardening guidelines.",
      },
      {
        id: "sec-asg-2",
        number: 2,
        title: "OWASP Top 10 Vulnerability Exploitation & Burp Suite Lab",
        badge: "Milestone 02: Web Vulnerability Audit",
        difficulty: "Intermediate",
        estimatedHours: 60,
        points: 7,
        description: "Identify and exploit OWASP Top 10 vulnerabilities (SQLi, Stored XSS, CSRF, IDOR) in a controlled staging application.",
        problemStatement: "Utilize Burp Suite to intercept and fuzz HTTP requests, perform SQL injection database extraction, execute authenticated IDOR privilege escalation, and craft proof-of-concept exploit scripts.",
        deliverables: [
          "Step-by-step Proof of Concept (PoC) exploit walkthroughs for 5 distinct vulnerabilities",
          "Burp Suite repeater/intruder payload logs and response captures",
          "Defensive code remediation snippets demonstrating parameterized queries and input sanitization",
        ],
        techRequirements: ["Burp Suite Community/Pro", "OWASP Top 10", "SQL Injection", "XSS & CSRF", "Python Exploit Scripts"],
        submissionGuidelines: "Include the vulnerability report, PoC scripts, and sanitized payload logs in your ZIP file.",
      },
      {
        id: "sec-asg-3",
        number: 3,
        title: "Executive Penetration Testing Audit Report & Defense Hardening",
        badge: "Milestone 03: Grand Capstone",
        difficulty: "Advanced (Production)",
        estimatedHours: 60,
        points: 7,
        description: "Author an industry-standard Penetration Testing Report with CVSS 3.1 scoring, executive summary, and zero-trust configuration.",
        problemStatement: "Deliver a formal corporate cybersecurity audit report detailing discovered vulnerabilities, CVSS 3.1 severity scores, business impact analysis, CSP/HSTS security header policies, and complete defense hardening blueprints.",
        deliverables: [
          "Executive Penetration Test Report (A4 PDF) formatted with corporate letterhead",
          "CVSS v3.1 calculation matrix mapping technical findings to business risk",
          "Security configuration files (Nginx headers, WAF rules, CORS policies) in ZIP archive",
        ],
        techRequirements: ["CVSS v3.1 Calculator", "Security Headers (CSP, HSTS)", "WAF Rules", "Report Writing"],
        submissionGuidelines: "Upload the penetration test report PDF, GitHub repository, and complete security audit ZIP archive for admin verification.",
      },
    ],
  },
];

